In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('RestoInfo_cleaned.csv')

In [3]:
data

,Unnamed: 0,ID,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,...,dish_liked7,cuisines1,cuisines2,cuisines3,cuisines4,cuisines5,cuisines6,cuisines7,cuisines8,menu_item_count
0,0,46019,Unique Brew Cafe Resto,No,No,NaN,0,Indiranagar,['Quick Bites'],NaN,...,NaN,Fast Food,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,28849,Jayanthi Sagar,No,No,3.1 /5,21,Koramangala 5th Block,['Quick Bites'],NaN,...,NaN,South Indian,North Indian,Chinese,NaN,NaN,NaN,NaN,NaN,0
2,2,19855,Rock Stone Ice Cream Factory,Yes,No,4.0/5,131,BTM,['Dessert Parlor'],"['Icecream Cake', ' Brownie', ' Waffles', ' Ch...",...,NaN,Ice Cream,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75
3,3,35188,Punjabi by Nature 2.0,No,No,4.2 /5,3236,BTM,"['Casual Dining', ' Microbrewery']","['Paneer Tikki', ' Mutton Raan', ' Mango Marga...",...,Kheer,North Indian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,7070,Rayalaseema Chefs,Yes,Yes,3.9/5,225,Marathahalli,['Casual Dining'],"['Bamboo Chicken', ' Butter Naan', ' Mutton Bi...",...,Jowar Roti,North Indian,Biryani,Andhra,Chinese,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2063,2064,8778,Zeeshan,Yes,No,3.8/5,214,Koramangala 7th Block,['Casual Dining'],"['Rolls', ' Kathi Roll', ' Mutton Roll', ' Chi...",...,Bengali Style Biryani,North Indian,Kebab,Biryani,Rolls,NaN,NaN,NaN,NaN,0
2064,2065,18086,Zaica Dine & Wine,Yes,Yes,4.0/5,1013,Indiranagar,['Casual Dining'],"['Chocolate Pani Puri', ' Butter Chicken', ' G...",...,Biryani,North Indian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2065,2066,46112,Murphy's Brewhouse - The Paul Bangalore,No,Yes,4.3 /5,2039,Domlur,"['Pub', ' Microbrewery']","['Chicken Bruschetta', ' Tandoori Chicken', ' ...",...,Stout,Continental,North Indian,Finger Food,NaN,NaN,NaN,NaN,NaN,0
2066,2067,10808,Cee Yem,No,No,NaN,0,BTM,['Quick Bites'],NaN,...,NaN,South Indian,Kerala,North Indian,NaN,NaN,NaN,NaN,NaN,0
2067,2068,28875,Cauvery Fast Food,No,No,3.2 /5,4,Ejipura,['Quick Bites'],NaN,...,NaN,Chinese,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0